### ISSUE TITLE
Regarding examples['dpr']

### ISSUE THREAD

**Issue by xfen974** [yasumasaonoe/creak#1]
Dear author,

Thank you for your code and data. We have read through the run_classifiers.py and run_seq2seq_classifiers.py files and noticed that the training data doesn't include the DPR component. We wonder if you can kindly share with us how the examples['dpr'] are generated. Can you point us to the source code involving this part of the generation?

Thanks for your help!

**Comment by yasumasaonoe** [comment]
Hi! 

We used the [DPR](https://github.com/facebookresearch/DPR) code with [the model used for KILT](https://github.com/facebookresearch/KILT/blob/main/kilt/retrievers/README.md#download-models-1). After retrieving passages, we added the 'dpr' field to each example that contains a list of passages.

Thanks!
